"use strict";

const ADMIN_PASSWORD = "midnight2026";

let adminClickCount=0,adminClickTimer=null;
document.getElementById("brandLogo").addEventListener("click",function(){adminClickCount++;if(adminClickCount===5){showAdminLogin();adminClickCount=0}clearTimeout(adminClickTimer);adminClickTimer=setTimeout(()=>{adminClickCount=0},2000)});

function showAdminLogin(){const modal=document.getElementById("modal");modal.classList.remove("hidden");document.getElementById("modalBox").innerHTML=`<button class="close" id="closeAdminModal">×</button><div class="section-title" style="margin-top:3px">🔐 Вход в админ-панель</div><div id="adminLoginForm"><input type="password" id="adminPasswordInput" class="admin-input" placeholder="Введите пароль"><button class="btn primary" id="adminLoginBtn" style="width:100%;margin-top:8px;">Войти</button><button class="btn" id="closeAdminBtn" style="width:100%;margin-top:6px;">Закрыть</button></div><div id="adminContent" style="display:none;margin-top:12px;"></div>`;document.getElementById("closeAdminModal").onclick=()=>modal.classList.add("hidden");document.getElementById("closeAdminBtn").onclick=()=>modal.classList.add("hidden");document.getElementById("adminLoginBtn").onclick=function(){const pass=document.getElementById("adminPasswordInput").value;if(pass===ADMIN_PASSWORD){document.getElementById("adminLoginForm").style.display="none";document.getElementById("adminContent").style.display="block";renderAdminPanel()}else{toast("❌ Неверный пароль!")}}}
function closeAdminPanel(){document.getElementById("modal").classList.add("hidden")}
function renderAdminPanel(){const container=document.getElementById("adminContent");container.innerHTML=`<div class="admin-grid"><button class="btn primary" onclick="adminTab('books')">📚 Книги</button><button class="btn" onclick="adminTab('playlist')">🎵 Плейлисты</button><button class="btn" onclick="adminTab('announce')">📢 Анонсы</button><button class="btn" onclick="adminTab('stats')">📊 Статистика</button></div><div id="adminTabContent"></div><button class="btn" onclick="closeAdminPanel()" style="width:100%;margin-top:12px;">🚪 Выйти</button>`;adminTab("books")}
function adminTab(tab){const container=document.getElementById("adminTabContent");if(tab==="books")renderAdminBooks(container);if(tab==="playlist")renderAdminPlaylists(container);if(tab==="announce")renderAdminAnnounce(container);if(tab==="stats")renderAdminStats(container)}

// ---- КНИГИ ----
function renderAdminBooks(container){let html=`<div style="margin-bottom:12px;"><h3 style="color:var(--silver2);">📚 Книги (${state.books.length})</h3><button class="btn primary" onclick="showAddBookForm()" style="width:100%;">➕ Добавить книгу</button></div><div id="adminBookList">`;state.books.forEach(book=>{const qCount=Array.isArray(book.quotes)?book.quotes.length:0;const tCount=Array.isArray(book.triggers)?book.triggers.length:0;html+=`<div class="admin-item"><div><div class="admin-item-title">${book.cover_emoji||"📖"} ${h(book.title)}</div><div class="admin-item-sub">${h(book.author)} · 💬 ${qCount} · 🩸 ${tCount}</div></div><div class="admin-btn-group"><button class="admin-btn wine" onclick="editBook(${book.id})">✏️</button><button class="admin-btn" onclick="editQuotes(${book.id})">💬</button><button class="admin-btn danger" onclick="deleteBook(${book.id})">🗑️</button></div></div>`});html+=`</div>`;container.innerHTML=html}
function showAddBookForm(){const container=document.getElementById("adminTabContent");container.innerHTML=`<div class="admin-box"><h3 style="color:var(--silver2);">➕ Новая книга</h3><input type="text" id="newTitle" class="admin-input" placeholder="Название"><input type="text" id="newAuthor" class="admin-input" placeholder="Автор"><input type="text" id="newTrops" class="admin-input" placeholder="Тропы (через запятую)"><input type="text" id="newTriggers" class="admin-input" placeholder="Триггеры (через запятую)"><textarea id="newDescription" class="admin-input" rows="3" placeholder="Аннотация"></textarea><input type="text" id="newCover" class="admin-input" placeholder="Обложка (эмодзи или ссылка)"><input type="text" id="newSeries" class="admin-input" placeholder="Серия (если есть)"><h4 style="color:var(--muted);margin:12px 0 6px;">💬 Цитаты (каждая с новой строки)</h4><textarea id="newQuotes" class="admin-input" rows="3" placeholder="Цитата 1&#10;Цитата 2&#10;Цитата 3"></textarea><button class="btn primary" onclick="saveNewBook()" style="width:100%;margin-top:8px;">💾 Сохранить книгу</button><button class="btn" onclick="adminTab('books')" style="width:100%;margin-top:4px;">↩️ Назад</button></div>`}
function saveNewBook(){const quotesText=document.getElementById("newQuotes").value;const quotesArray=quotesText.split('\n').map(q=>q.trim()).filter(Boolean);const triggersText=document.getElementById("newTriggers").value;const triggersArray=triggersText.split(',').map(t=>t.trim()).filter(Boolean);const newBook={id:state.books.length+1,title:document.getElementById("newTitle").value||"Без названия",author:document.getElementById("newAuthor").value||"Неизвестный автор",trops:document.getElementById("newTrops").value.split(",").map(t=>t.trim()).filter(Boolean),triggers:triggersArray,description:document.getElementById("newDescription").value||"Описание пока не добавлено.",cover_emoji:document.getElementById("newCover").value||"📖",series:document.getElementById("newSeries").value||null,series_order:null,quotes:quotesArray,rating:0,status:"active"};state.books.push(newBook);storageSet(CACHE_KEY,{books:state.books,playlists:state.playlists,files:state.files,covers:state.covers,announcements:state.announcements,updatedAt:Date.now()});toast(`✅ Книга добавлена! ${quotesArray.length} цитат, ${triggersArray.length} триггеров.`);adminTab("books");render()}
function deleteBook(id){if(!confirm("Удалить книгу?"))return;state.books=state.books.filter(b=>b.id!==id);storageSet(CACHE_KEY,{books:state.books,playlists:state.playlists,files:state.files,covers:state.covers,announcements:state.announcements,updatedAt:Date.now()});toast("🗑️ Книга удалена");adminTab("books");render()}
function editBook(id){const book=state.books.find(b=>b.id===id);if(!book)return;const container=document.getElementById("adminTabContent");container.innerHTML=`<div class="admin-box"><h3 style="color:var(--silver2);">✏️ Редактировать: ${h(book.title)}</h3><input type="text" id="editTitle" class="admin-input" value="${h(book.title)}" placeholder="Название"><input type="text" id="editAuthor" class="admin-input" value="${h(book.author)}" placeholder="Автор"><input type="text" id="editTrops" class="admin-input" value="${(Array.isArray(book.trops)?book.trops:arr(book.trops)).join(", ")}" placeholder="Тропы"><input type="text" id="editTriggers" class="admin-input" value="${(Array.isArray(book.triggers)?book.triggers:arr(book.triggers)).join(", ")}" placeholder="Триггеры"><textarea id="editDescription" class="admin-input" rows="3" placeholder="Аннотация">${h(book.description)}</textarea><input type="text" id="editCover" class="admin-input" value="${h(book.cover_emoji)}" placeholder="Обложка"><input type="text" id="editSeries" class="admin-input" value="${h(book.series||"")}" placeholder="Серия"><button class="btn primary" onclick="saveEditBook(${id})" style="width:100%;margin-top:8px;">💾 Сохранить изменения</button><button class="btn" onclick="adminTab('books')" style="width:100%;margin-top:4px;">↩️ Назад</button></div>`}
function saveEditBook(id){const book=state.books.find(b=>b.id===id);if(!book)return;book.title=document.getElementById("editTitle").value||"Без названия";book.author=document.getElementById("editAuthor").value||"Неизвестный автор";book.trops=document.getElementById("editTrops").value.split(",").map(t=>t.trim()).filter(Boolean);book.triggers=document.getElementById("editTriggers").value.split(",").map(t=>t.trim()).filter(Boolean);book.description=document.getElementById("editDescription").value||"Описание пока не добавлено.";book.cover_emoji=document.getElementById("editCover").value||"📖";book.series=document.getElementById("editSeries").value||null;storageSet(CACHE_KEY,{books:state.books,playlists:state.playlists,files:state.files,covers:state.covers,announcements:state.announcements,updatedAt:Date.now()});toast("✅ Изменения сохранены!");adminTab("books");render()}

// ---- ЦИТАТЫ ----
function editQuotes(id){const book=state.books.find(b=>b.id===id);if(!book)return;let qArr=Array.isArray(book.quotes)?book.quotes:arr(book.quotes);const container=document.getElementById("adminTabContent");container.innerHTML=`<div class="admin-box"><h3 style="color:var(--silver2);">💬 Цитаты: ${h(book.title)}</h3><div id="quotesList">${qArr.length===0?'<div style="color:var(--muted);padding:8px 0;">Цитат пока нет.</div>':''}${qArr.map((q,i)=>`<div style="display:flex;gap:8px;align-items:center;margin:4px 0;"><span style="color:var(--muted);font-size:12px;min-width:24px;">${i+1}.</span><input type="text" class="admin-input quote-input" value="${h(q)}" style="flex:1;" data-index="${i}"><button class="admin-btn danger" onclick="removeQuote(this,${id})">✕</button></div>`).join('')}</div><button class="btn" onclick="addQuoteField(${id})" style="width:100%;margin:8px 0;">➕ Добавить цитату</button><button class="btn primary" onclick="saveQuotes(${id})" style="width:100%;">💾 Сохранить все цитаты</button><button class="btn" onclick="adminTab('books')" style="width:100%;margin-top:4px;">↩️ Назад</button></div>`}
function addQuoteField(id){const list=document.getElementById("quotesList");const idx=list.querySelectorAll('.quote-input').length;const div=document.createElement('div');div.style.cssText="display:flex;gap:8px;align-items:center;margin:4px 0;";div.innerHTML=`<span style="color:var(--muted);font-size:12px;min-width:24px;">${idx+1}.</span><input type="text" class="admin-input quote-input" placeholder="Введите цитату..." style="flex:1;" data-index="${idx}"><button class="admin-btn danger" onclick="removeQuote(this,${id})">✕</button>`;list.appendChild(div)}
function removeQuote(btn,id){const div=btn.closest('div');if(div&&div.parentNode){div.remove();const list=document.getElementById("quotesList");const items=list.querySelectorAll('div');items.forEach((el,i)=>{const num=el.querySelector('span:first-child');if(num)num.textContent=`${i+1}.`})}}
function saveQuotes(id){const book=state.books.find(b=>b.id===id);if(!book)return;const inputs=document.querySelectorAll('.quote-input');const quotes=[];inputs.forEach(i=>{const t=i.value.trim();if(t)quotes.push(t)});book.quotes=quotes;storageSet(CACHE_KEY,{books:state.books,playlists:state.playlists,files:state.files,covers:state.covers,announcements:state.announcements,updatedAt:Date.now()});toast(`✅ ${quotes.length} цитат сохранено!`);adminTab('books');render()}

// ---- ПЛЕЙЛИСТЫ ----
function renderAdminPlaylists(container){let html=`<h3 style="color:var(--silver2);">🎵 Плейлисты</h3><div style="margin-bottom:12px;"><select id="playlistBookSelect" class="admin-input"><option value="">Выберите книгу</option>${state.books.map(b=>`<option value="${b.id}">${b.cover_emoji||"📖"} ${h(b.title)}</option>`).join('')}</select><button class="btn primary" onclick="addTrackToPlaylist()" style="width:100%;margin-top:6px;">➕ Добавить трек</button></div><div id="playlistTracks"></div>`;container.innerHTML=html;document.getElementById("playlistBookSelect").addEventListener("change",function(){renderPlaylistTracks(this.value)})}
function renderPlaylistTracks(bookId){const container=document.getElementById("playlistTracks");if(!bookId){container.innerHTML='<div style="color:var(--muted);padding:12px;">Выберите книгу</div>';return}const tracks=state.playlists.filter(p=>String(p.book_id)===String(bookId));if(!tracks.length){container.innerHTML='<div style="color:var(--muted);padding:12px;">Нет треков для этой книги</div>';return}container.innerHTML=tracks.map((t,i)=>`<div class="admin-item"><div><div class="admin-item-title">${i+1}. ${h(t.track_name||"Без названия")}</div><div class="admin-item-sub">${h(t.artist||"—")}</div></div><button class="admin-btn danger" onclick="removeTrackFromPlaylist('${t.id}')">🗑️</button></div>`).join('')}
function addTrackToPlaylist(){const bookId=document.getElementById("playlistBookSelect").value;if(!bookId){toast("Выберите книгу");return}const trackName=prompt("Название трека:");if(!trackName)return;const artist=prompt("Исполнитель:")||"—";const url=prompt("Ссылка на аудиофайл (MP3):");if(!url){toast("Ссылка обязательна");return}const newTrack={id:state.playlists.length+1,book_id:bookId,track_name:trackName,artist:artist,file_url:url,mood:""};state.playlists.push(newTrack);storageSet(CACHE_KEY,{books:state.books,playlists:state.playlists,files:state.files,covers:state.covers,announcements:state.announcements,updatedAt:Date.now()});toast("✅ Трек добавлен!");renderPlaylistTracks(bookId)}
function removeTrackFromPlaylist(trackId){if(!confirm("Удалить трек?"))return;state.playlists=state.playlists.filter(t=>String(t.id)!==String(trackId));storageSet(CACHE_KEY,{books:state.books,playlists:state.playlists,files:state.files,covers:state.covers,announcements:state.announcements,updatedAt:Date.now()});toast("🗑️ Трек удалён");const select=document.getElementById("playlistBookSelect");if(select)renderPlaylistTracks(select.value)}

// ---- АНОНСЫ ----
function renderAdminAnnounce(container){const a=state.announcements[0]||{title:"",author:"",teaser:"",release_date:"",active:"TRUE"};container.innerHTML=`<div class="admin-box"><h3 style="color:var(--silver2);">📢 Анонс</h3><input type="text" id="annTitle" class="admin-input" value="${h(a.title)}" placeholder="Название"><input type="text" id="annAuthor" class="admin-input" value="${h(a.author)}" placeholder="Автор"><input type="text" id="annTeaser" class="admin-input" value="${h(a.teaser)}" placeholder="Тизер"><input type="date" id="annDate" class="admin-input" value="${a.release_date||""}"><button class="btn primary" onclick="saveAnnounce()" style="width:100%;margin-top:8px;">💾 Сохранить анонс</button></div>`}
function saveAnnounce(){state.announcements=[{id:1,title:document.getElementById("annTitle").value||"Скоро",author:document.getElementById("annAuthor").value||"",teaser:document.getElementById("annTeaser").value||"Новая книга скоро появится.",release_date:document.getElementById("annDate").value||"",active:"TRUE",cover_emoji:"🌙"}];storageSet(CACHE_KEY,{books:state.books,playlists:state.playlists,files:state.files,covers:state.covers,announcements:state.announcements,updatedAt:Date.now()});toast("✅ Анонс сохранён!");adminTab("announce");render()}

// ---- СТАТИСТИКА ----
function renderAdminStats(container){let html=`<h3 style="color:var(--silver2);">📊 Статистика</h3>`;state.books.forEach(book=>{const views=getViews(book.id),downloads=getDownloads(book.id),rating=getBookRating(book);html+=`<div class="admin-item"><div><div class="admin-item-title">${book.cover_emoji||"📖"} ${h(book.title)}</div><div class="admin-item-sub">👁️ ${views} просмотров · ⬇️ ${downloads} скачиваний · ⭐ ${rating.toFixed(1)}</div></div></div>`});container.innerHTML=html}
